services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: supersecret
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 30s
      retries: 10
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/ZZZ_migration.sql


  pgadmin4:
    image: dcagatay/pwless-pgadmin4:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 7777:80
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "omdb"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
    restart: unless-stopped
